using System.Security.Cryptography;
using System.Text;
using Athena.WorldCompiler.Rathena.Syntax;

namespace Athena.WorldCompiler.Generation;

internal readonly record struct MapId(string Value);
internal readonly record struct NpcId(string Value);
internal readonly record struct ItemId(uint Value);
internal readonly record struct MonsterId(uint Value);
internal readonly record struct QuestId(uint Value);
internal readonly record struct SkillId(uint Value);
internal sealed record LoweredWarp(NpcId Id,string Name,MapId SourceMap,ushort X,ushort Y,ushort RadiusX,ushort RadiusY,MapId DestinationMap,ushort DestinationX,ushort DestinationY,bool HasActor,string SourceFile,int SourceLine);
internal sealed record LoweredWorld(IReadOnlyList<LoweredWarp> Warps);
internal enum ScriptControlFlowShape { Structured, StateMachine }
internal sealed record LoweredScriptPlan(ScriptControlFlowShape Shape,string Reason);
internal static class ScriptControlFlowLowerer
{
    public static LoweredScriptPlan Plan(CompilationUnitSyntax syntax)
    {
        var hasArbitraryJump=syntax.Statements.Any(s=>s is GotoStatementSyntax or LabelStatementSyntax);
        return hasArbitraryJump
            ? new(ScriptControlFlowShape.StateMachine,"Labels/goto lower to explicit generated states so control flow never crosses an async suspension as C# goto.")
            : new(ScriptControlFlowShape.Structured,"Structured syntax can be emitted as structured C#.");
    }
}
internal static class WorldLowerer
{
    public static LoweredWorld Lower(IEnumerable<WorldEntityDefinition> entities)=>new(entities.SelectMany(e=>e.Triggers.SelectMany(t=>t.Actions.OfType<WarpAction>().Select(w=>new LoweredWarp(new(e.Id),e.Actor?.Name??e.Id,new(t.Map),t.X,t.Y,t.RadiusX,t.RadiusY,new(w.Map),w.X,w.Y,e.Actor is not null,e.Source.File,e.Source.Line)))).OrderBy(x=>x.Id.Value,StringComparer.Ordinal).ToArray());
}
internal static class CSharpWorldEmitter
{
    public static string Emit(LoweredWorld world,string upstreamCommit,string compilerVersion="1",string @namespace="Athena.Net.MapServer.Generated.World.Izlude",string className="GeneratedWarps")
    {
        var body=new StringBuilder("// <auto-generated>\n// Generated by Athena.WorldCompiler from pinned rAthena.\n// Do not edit this file directly.\n// </auto-generated>\nusing Athena.Net.MapServer.World;\n\nnamespace ").Append(@namespace).Append(";\n\ninternal static class ").Append(className).Append("\n{\n    internal static readonly WarpDefinition[] All =\n    [\n");
        foreach(var w in world.Warps) body.Append("        new(\"").Append(E(w.Name)).Append("\", \"").Append(E(w.SourceMap.Value)).Append("\", ").Append(w.X).Append(", ").Append(w.Y).Append(", ").Append(w.RadiusX).Append(", ").Append(w.RadiusY).Append(", \"").Append(E(w.DestinationMap.Value)).Append("\", ").Append(w.DestinationX).Append(", ").Append(w.DestinationY).Append(", ").Append(w.HasActor?"true":"false").Append(", \"").Append(E(w.SourceFile)).Append("\", ").Append(w.SourceLine).Append("),\n");
        body.Append("    ];\n}\n");
        var hash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(body.ToString()))).ToLowerInvariant();
        body.Append("\ninternal static class WorldBuildInfo\n{\n    internal const string RathenaCommit = \"").Append(E(upstreamCommit)).Append("\";\n    internal const string CompilerVersion = \"").Append(E(compilerVersion)).Append("\";\n    internal const string WorldHash = \"").Append(hash).Append("\";\n}\n"); return body.ToString();
    }
    private static string E(string value)=>value.Replace("\\","\\\\",StringComparison.Ordinal).Replace("\"","\\\"",StringComparison.Ordinal);
}

internal static class CSharpActorEmitter
{
    public static string Emit(IEnumerable<WorldEntityDefinition> entities, string upstreamCommit)
    {
        var actors = entities.Where(entity => entity.Actor is not null).OrderBy(entity => entity.Id, StringComparer.Ordinal).ToArray();
        var output = new StringBuilder("// <auto-generated>\n// Generated by Athena.WorldCompiler.\n// Source: pinned legacy/rathena NPC declarations.\n// rAthena commit: ")
            .Append(upstreamCommit).Append("\n// Do not edit this file directly.\n// </auto-generated>\nusing Athena.Net.MapServer.World;\n\nnamespace Athena.Net.MapServer.Generated.World.Izlude;\n\ninternal static class GeneratedTutorialActors\n{\n    internal static readonly WorldEntityDefinition[] All =\n    [\n");
        foreach (var entity in actors)
        {
            var actor = entity.Actor!;
            output.Append("        new(1, \"").Append(E(entity.Id)).Append("\", \"").Append(E(entity.Kind)).Append("\", new(\"")
                .Append(E(actor.Name)).Append("\", \"").Append(E(actor.Map)).Append("\", ").Append(actor.X).Append(", ").Append(actor.Y).Append(", ")
                .Append(actor.Direction).Append(", ").Append(actor.Class).Append(", ").Append(actor.EffectState)
                .Append("), [], [], new(\"rAthena\", \"").Append(E(entity.Source.Commit)).Append("\", \"").Append(E(Canonical(entity.Source.File))).Append("\", ")
                .Append(entity.Source.Line).AppendLine(")),");
        }
        output.Append("    ];\n}\n");
        return output.ToString();
    }

    private static string Canonical(string path)
    {
        var normalized = path.Replace('\\', '/');
        var index = normalized.IndexOf("legacy/rathena/", StringComparison.Ordinal);
        return index >= 0 ? normalized[index..] : normalized;
    }
    private static string E(string value) => value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
}
