using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

namespace Athena.WorldCompiler.Generation;

// Compiles one pinned rAthena item_db_etc.yml (or sibling) `- Id:` block.
// Stackability follows item_data::isStackable (itemdb.cpp): every Type except
// Weapon/Armor/PetEgg/PetArmor/ShadowGear is stackable. Etc items (Wood's
// Type) are always stackable, so this compiler does not need to special-case
// Wood - it reads Type generically the same way it reads AegisName/Id.
internal static class ItemDataCompiler
{
    private static readonly HashSet<string> NonStackableTypes = new(StringComparer.Ordinal) { "Weapon", "Armor", "PetEgg", "PetArmor", "ShadowGear" };

    internal sealed record ItemDefinitionData(int Id, string AegisName, string Name, string Type, bool Stackable);

    internal static ItemDefinitionData ReadItemDefinition(string itemDbYaml, int itemId)
    {
        var marker = $"  - Id: {itemId.ToString(CultureInfo.InvariantCulture)}\n";
        var start = itemDbYaml.IndexOf(marker, StringComparison.Ordinal);
        if (start < 0) throw new ArgumentException($"Item Id {itemId} was not found in the pinned item database.");
        var next = itemDbYaml.IndexOf("\n  - Id: ", start + marker.Length, StringComparison.Ordinal);
        var block = next >= 0 ? itemDbYaml[start..(next + 1)] : itemDbYaml[start..];

        var aegisName = RequiredScalar(block, "AegisName");
        var name = RequiredScalar(block, "Name");
        var type = RequiredScalar(block, "Type");
        return new ItemDefinitionData(itemId, aegisName, name, type, !NonStackableTypes.Contains(type));
    }

    internal static string Generate(ItemDefinitionData item, string commit, string className, string constantName, string sourceFile, int sourceLine)
    {
        return new StringBuilder()
            .AppendLine("// <auto-generated>")
            .AppendLine("// Generated by Athena.WorldCompiler.")
            .Append("// Source: ").Append(sourceFile).Append(':').Append(sourceLine.ToString(CultureInfo.InvariantCulture)).AppendLine()
            .Append("// rAthena commit: ").AppendLine(commit)
            .AppendLine("// Do not edit this file directly.")
            .AppendLine("// </auto-generated>")
            .AppendLine("using Athena.Net.MapServer.World;")
            .AppendLine()
            // Global game data ("what is item <id>") - referenceable from any world slice, not
            // world/placement data, so this does not live under Generated.World.Izlude.Academy.
            .AppendLine("namespace Athena.Net.MapServer.Generated.GameData.Items;")
            .AppendLine()
            .Append("internal static class ").AppendLine(className)
            .AppendLine("{")
            .Append("    internal static readonly ItemDefinition ").Append(constantName).AppendLine(" = new(")
            .Append("        Id: ").Append(item.Id).AppendLine(",")
            .Append("        AegisName: \"").Append(item.AegisName).AppendLine("\",")
            .Append("        Name: \"").Append(item.Name).AppendLine("\",")
            .Append("        Stackable: ").Append(item.Stackable ? "true" : "false").AppendLine(",")
            .Append("        Source: new WorldSourceInfo(\"rAthena\", \"").Append(commit).Append("\", \"").Append(sourceFile).Append("\", ").Append(sourceLine).AppendLine("));")
            .AppendLine("}")
            .ToString();
    }

    private static string RequiredScalar(string block, string field)
    {
        var match = Regex.Match(block, $@"^    {Regex.Escape(field)}: (.+)$", RegexOptions.Multiline);
        if (!match.Success) throw new ArgumentException($"Pinned item block has no '{field}' field.");
        return match.Groups[1].Value;
    }
}
