using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

namespace Athena.WorldCompiler.Generation;

// Compiles one pinned rAthena item_db_etc.yml (or sibling) `- Id:` block.
// Stackability follows item_data::isStackable (itemdb.cpp): every Type except
// Weapon/Armor/PetEgg/PetArmor/ShadowGear is stackable. Etc items (Wood's
// Type) are always stackable, so this compiler does not need to special-case
// Wood - it reads Type generically the same way it reads AegisName/Id.
internal static class ItemDataCompiler
{
    private static readonly HashSet<string> NonStackableTypes = new(StringComparer.Ordinal) { "Weapon", "Armor", "PetEgg", "PetArmor", "ShadowGear" };

    // Attack/WeaponLevel are general item_db_equip.yml columns (see the file's own header
    // comment: "WeaponLevel  Weapon level. (Default: 1 for Weapons)"), read only for
    // Type: Weapon rows - matching pinned status.cpp:3940's own
    // `sd->inventory_data[index]->type == IT_WEAPON` gate before reading atk/weapon_level.
    internal sealed record ItemDefinitionData(int Id, string AegisName, string Name, string Type, bool Stackable, int? Attack, int? WeaponLevel);

    internal static ItemDefinitionData ReadItemDefinition(string itemDbYaml, int itemId)
    {
        var marker = $"  - Id: {itemId.ToString(CultureInfo.InvariantCulture)}\n";
        var start = itemDbYaml.IndexOf(marker, StringComparison.Ordinal);
        if (start < 0) throw new ArgumentException($"Item Id {itemId} was not found in the pinned item database.");
        var next = itemDbYaml.IndexOf("\n  - Id: ", start + marker.Length, StringComparison.Ordinal);
        var block = next >= 0 ? itemDbYaml[start..(next + 1)] : itemDbYaml[start..];

        var aegisName = RequiredScalar(block, "AegisName");
        var name = RequiredScalar(block, "Name");
        var type = RequiredScalar(block, "Type");
        var isWeapon = type == "Weapon";
        // WeaponLevel defaults to 1 when the pinned YAML omits it for a weapon row (file header
        // comment: "Default: 1 for Weapons"), matching pinned rAthena's own item_db loader default.
        var attack = isWeapon ? int.Parse(RequiredScalar(block, "Attack"), CultureInfo.InvariantCulture) : (int?)null;
        var weaponLevel = isWeapon ? (OptionalScalar(block, "WeaponLevel") is { } wl ? int.Parse(wl, CultureInfo.InvariantCulture) : 1) : (int?)null;
        return new ItemDefinitionData(itemId, aegisName, name, type, !NonStackableTypes.Contains(type), attack, weaponLevel);
    }

    internal static string Generate(ItemDefinitionData item, string commit, string className, string constantName, string sourceFile, int sourceLine)
    {
        var isWeapon = item.Type == "Weapon";
        var typeName = isWeapon ? "WeaponItemDefinition" : "EtcItemDefinition";

        var builder = new StringBuilder()
            .AppendLine("// <auto-generated>")
            .AppendLine("// Generated by Athena.WorldCompiler.")
            .Append("// Source: ").Append(sourceFile).Append(':').Append(sourceLine.ToString(CultureInfo.InvariantCulture)).AppendLine()
            .Append("// rAthena commit: ").AppendLine(commit)
            .AppendLine("// Do not edit this file directly.")
            .AppendLine("// </auto-generated>")
            .AppendLine("using Athena.Net.MapServer.World;")
            .AppendLine()
            // Global game data ("what is item <id>") - referenceable from any world slice, not
            // world/placement data, so this does not live under Generated.World.Izlude.Academy.
            .AppendLine("namespace Athena.Net.MapServer.Generated.GameData.Items;")
            .AppendLine()
            .Append("internal static class ").AppendLine(className)
            .AppendLine("{")
            .Append("    internal static readonly ").Append(typeName).Append(' ').Append(constantName).AppendLine(" = new(")
            .Append("        Id: ").Append(item.Id).AppendLine(",")
            .Append("        AegisName: \"").Append(item.AegisName).AppendLine("\",")
            .Append("        Name: \"").Append(item.Name).AppendLine("\",")
            .Append("        Stackable: ").Append(item.Stackable ? "true" : "false").AppendLine(",");

        if (isWeapon)
        {
            builder
                .Append("        Attack: ").Append(item.Attack!.Value.ToString(CultureInfo.InvariantCulture)).AppendLine(",")
                .Append("        WeaponLevel: ").Append(item.WeaponLevel!.Value.ToString(CultureInfo.InvariantCulture)).AppendLine(",");
        }

        builder
            .Append("        Source: new WorldSourceInfo(\"rAthena\", \"").Append(commit).Append("\", \"").Append(sourceFile).Append("\", ").Append(sourceLine).AppendLine("));")
            .AppendLine("}");
        return builder.ToString();
    }

    private static string RequiredScalar(string block, string field)
    {
        var match = Regex.Match(block, $@"^    {Regex.Escape(field)}: (.+)$", RegexOptions.Multiline);
        if (!match.Success) throw new ArgumentException($"Pinned item block has no '{field}' field.");
        return match.Groups[1].Value;
    }

    private static string? OptionalScalar(string block, string field)
    {
        var match = Regex.Match(block, $@"^    {Regex.Escape(field)}: (.+)$", RegexOptions.Multiline);
        return match.Success ? match.Groups[1].Value : null;
    }
}
