using System.Globalization;
using System.Text;
using Athena.WorldCompiler.Lowering;
using Athena.WorldCompiler.Rathena.Syntax;

namespace Athena.WorldCompiler.Generation;

internal sealed record GeneratedNpcMetadata(
    string Namespace,
    string ClassName,
    string EntityId,
    string EntityKind,
    string NpcName,
    string Map,
    ushort X,
    ushort Y,
    byte Direction,
    ushort Class,
    ushort RadiusX,
    ushort RadiusY,
    string Trigger,
    string? BaseNpcName,
    string SourceFile,
    int CodeLine,
    int DeclarationLine,
    string SourceCommit,
    uint EffectState = 0);

internal sealed record GeneratedDefinitionMetadata(
    string Namespace,
    string ClassName,
    string DefinitionId,
    string TemplateNpcName,
    string SourceFile,
    int DeclarationLine,
    string SourceCommit);

internal sealed record GeneratedTriggerMetadata(string Trigger, string SourceFile, int CodeLine, int DeclarationLine);

internal sealed record GeneratedPlacementMetadata(
    string PlacementId,
    string DefinitionId,
    string NpcName,
    string Map,
    ushort X,
    ushort Y,
    byte Direction,
    ushort Class,
    ushort RadiusX,
    ushort RadiusY,
    uint InitialEffectState,
    string SourceFile,
    int DeclarationLine,
    string SourceCommit);

internal static class NpcScriptEmitter
{
    // Definition-scoped: the shared INpcScript class body only, no per-placement registration literal.
    // Statement/expression emission is reused byte-for-byte from Emit(...) below.
    public static string EmitScriptClass(LoweredNpcScript script, GeneratedDefinitionMetadata definition, GeneratedTriggerMetadata trigger, string className)
    {
        var output = new StringBuilder();
        output.AppendLine("// <auto-generated>");
        output.AppendLine("// Generated by Athena.WorldCompiler.");
        output.Append("// Source: ").Append(definition.SourceFile).Append(':').Append(definition.DeclarationLine).AppendLine();
        output.Append("// rAthena commit: ").Append(definition.SourceCommit).AppendLine();
        output.AppendLine("// Do not edit this file directly.");
        output.AppendLine("// </auto-generated>");
        output.AppendLine("using Athena.Net.MapServer.World;");
        output.AppendLine("using Athena.Net.MapServer.World.GeneratedScripts;");
        output.AppendLine();
        output.Append("namespace ").Append(definition.Namespace).AppendLine();
        output.AppendLine("{");
        output.Append("internal sealed class ").Append(className).AppendLine(" : INpcScript");
        output.AppendLine("{");
        output.AppendLine("    public async Task ExecuteAsync(ScriptContext context, CancellationToken cancellationToken)");
        output.AppendLine("    {");
        output.Append("#line ").Append(trigger.CodeLine).Append(" \"").Append(Escape(trigger.SourceFile)).AppendLine("\"");
        var locals = FindLocals(script.Statements).Order(StringComparer.Ordinal).ToArray();
        foreach (var local in locals) output.Append("        string ").Append(Local(local)).AppendLine(" = string.Empty;");
        if (locals.Length > 0) output.AppendLine();
        foreach (var statement in script.Statements) EmitStatement(output, statement, 2);
        output.AppendLine("#line default");
        output.AppendLine("    }");
        output.AppendLine("}");
        output.AppendLine("}");
        return output.ToString();
    }

    public static string Emit(LoweredNpcScript script, GeneratedNpcMetadata metadata)
    {
        var output = new StringBuilder();
        output.AppendLine("// <auto-generated>");
        output.AppendLine("// Generated by Athena.WorldCompiler.");
        output.Append("// Source: ").Append(metadata.SourceFile).Append(':').Append(metadata.DeclarationLine).AppendLine();
        output.Append("// rAthena commit: ").Append(metadata.SourceCommit).AppendLine();
        output.AppendLine("// Do not edit this file directly.");
        output.AppendLine("// </auto-generated>");
        output.AppendLine("using Athena.Net.MapServer.World;");
        output.AppendLine("using Athena.Net.MapServer.World.GeneratedScripts;");
        output.AppendLine();
        output.Append("namespace ").Append(metadata.Namespace).AppendLine();
        output.AppendLine("{");
        output.Append("internal sealed class ").Append(metadata.ClassName).AppendLine(" : INpcScript");
        output.AppendLine("{");
        output.AppendLine("    public async Task ExecuteAsync(ScriptContext context, CancellationToken cancellationToken)");
        output.AppendLine("    {");
        output.Append("#line ").Append(metadata.CodeLine).Append(" \"").Append(Escape(metadata.SourceFile)).AppendLine("\"");
        var locals = FindLocals(script.Statements).Order(StringComparer.Ordinal).ToArray();
        foreach (var local in locals) output.Append("        string ").Append(Local(local)).AppendLine(" = string.Empty;");
        if (locals.Length > 0) output.AppendLine();
        foreach (var statement in script.Statements) EmitStatement(output, statement, 2);
        output.AppendLine("#line default");
        output.AppendLine("    }");
        output.AppendLine("}");
        output.AppendLine("}");
        output.AppendLine();
        EmitRegistry(output, metadata);
        return output.ToString();
    }

    private static void EmitStatement(StringBuilder output, LoweredScriptStatement statement, int depth)
    {
        var indent = new string(' ', depth * 4);
        switch (statement)
        {
            case LoweredBlock block:
                output.Append(indent).AppendLine("{"); foreach (var child in block.Statements) EmitStatement(output, child, depth + 1); output.Append(indent).AppendLine("}"); break;
            case LoweredIf conditional:
                output.Append(indent).Append("if ("); EmitExpression(output, conditional.Condition); output.AppendLine(")"); EmitEmbedded(output, conditional.Then, depth);
                if (conditional.Else is not null) { output.Append(indent).AppendLine("else"); EmitEmbedded(output, conditional.Else, depth); }
                break;
            case LoweredSwitch selection:
                output.Append(indent).Append("switch ("); EmitExpression(output, selection.Expression); output.AppendLine(")");
                output.Append(indent).AppendLine("{");
                foreach (var item in selection.Cases)
                {
                    output.Append(indent).Append("    ").Append(item.Value is null ? "default" : "case ");
                    if (item.Value is not null) EmitExpression(output, item.Value);
                    output.AppendLine(":");
                    foreach (var child in item.Statements) EmitStatement(output, child, depth + 2);
                    output.Append(indent).AppendLine("        break;");
                }
                output.Append(indent).AppendLine("}");
                break;
            case LoweredAssignment assignment:
                output.Append(indent).Append(Local(assignment.Variable)).Append(" = "); EmitExpression(output, assignment.Value); output.AppendLine(";"); break;
            case LoweredCommand command:
                EmitCommand(output, command, depth); break;
        }
    }

    private static void EmitEmbedded(StringBuilder output, LoweredScriptStatement statement, int depth)
    {
        if (statement is LoweredBlock) EmitStatement(output, statement, depth);
        else { output.Append(new string(' ', depth * 4)).AppendLine("{"); EmitStatement(output, statement, depth + 1); output.Append(new string(' ', depth * 4)).AppendLine("}"); }
    }

    private static void EmitCommand(StringBuilder output, LoweredCommand command, int depth)
    {
        var indent = new string(' ', depth * 4);
        switch (command.Name)
        {
            case "mes": output.Append(indent).Append("await context.MesAsync("); EmitExpression(output, command.Arguments[0]); output.AppendLine(", cancellationToken);"); break;
            case "next": output.Append(indent).AppendLine("await context.NextAsync(cancellationToken);"); break;
            case "close": output.Append(indent).AppendLine("await context.CloseAsync(cancellationToken);"); output.Append(indent).AppendLine("return;"); break;
            case "close2": output.Append(indent).AppendLine("await context.Close2Async(cancellationToken);"); break;
            case "setquest": EmitQuest(output, indent, "SetQuest", command.Arguments[0]); break;
            case "completequest": EmitQuest(output, indent, "CompleteQuest", command.Arguments[0]); break;
            case "warp": EmitTransfer(output, indent, "Warp", command.Arguments); break;
            case "savepoint": EmitTransfer(output, indent, "SetSavePoint", command.Arguments); break;
            case "cutin": output.Append(indent).Append("await context.CutinAsync("); EmitExpression(output, command.Arguments[0]); output.Append(", (byte)"); EmitExpression(output, command.Arguments[1]); output.AppendLine(", cancellationToken);"); break;
            case "npctalk": output.Append(indent).Append("await context.NpcTalkAsync("); EmitExpression(output, command.Arguments[0]); output.AppendLine(", cancellationToken);"); break;
            case "cloakonnpcself": output.Append(indent).AppendLine("await context.SetNpcCloakAsync(null, true, cancellationToken);"); break;
            case "cloakoffnpcself": output.Append(indent).Append("await context.SetNpcCloakAsync("); EmitExpression(output, command.Arguments[0]); output.AppendLine(", false, cancellationToken);"); break;
            case "navigateto": output.Append(indent).Append("await context.NavigateToAsync("); EmitExpression(output, command.Arguments[0]); output.Append(", (ushort)"); EmitExpression(output, command.Arguments[1]); output.Append(", (ushort)"); EmitExpression(output, command.Arguments[2]); output.AppendLine(", cancellationToken);"); break;
            case "specialeffect2": output.Append(indent).Append("await context.SpecialEffectAsync("); EmitExpression(output, command.Arguments[0]); output.AppendLine(", cancellationToken);"); break;
            case "heal": output.Append(indent).Append("await context.HealAsync("); EmitExpression(output, command.Arguments[0]); output.Append(", "); EmitExpression(output, command.Arguments[1]); output.AppendLine(", cancellationToken);"); break;
            case "skilleffect": output.Append(indent).Append("await context.SkillEffectAsync("); EmitExpression(output, command.Arguments[0]); output.Append(", "); EmitExpression(output, command.Arguments[1]); output.AppendLine(", cancellationToken);"); break;
            case "sc_start": output.Append(indent).Append("await context.StartStatusAsync("); EmitArguments(output, command.Arguments); output.AppendLine(", cancellationToken);"); break;
            case "getexp": output.Append(indent).Append("await context.GrantExperienceAsync("); EmitArguments(output, command.Arguments); output.AppendLine(", cancellationToken);"); break;
            case "end": break;
            case "select": throw new InvalidOperationException("select is emitted as an expression.");
        }
    }

    private static void EmitQuest(StringBuilder output, string indent, string method, LoweredScriptExpression quest)
    {
        output.Append(indent).Append("await context.").Append(method).Append("Async(new QuestId("); EmitExpression(output, quest); output.AppendLine("), cancellationToken);");
    }
    private static void EmitTransfer(StringBuilder output, string indent, string method, IReadOnlyList<LoweredScriptExpression> arguments)
    {
        output.Append(indent).Append("await context.").Append(method).Append("Async(");
        for (var index = 0; index < 3; index++) { if (index > 0) output.Append(", "); EmitExpression(output, arguments[index]); }
        output.AppendLine(", cancellationToken);");
    }

    private static void EmitExpression(StringBuilder output, LoweredScriptExpression expression)
    {
        switch (expression)
        {
            case LoweredLiteral { Value: string text }: output.Append('"').Append(Escape(text)).Append('"'); break;
            case LoweredLiteral literal: output.Append(Convert.ToString(literal.Value, CultureInfo.InvariantCulture)); break;
            case LoweredVariable variable: output.Append(Local(variable.Name)); break;
            case LoweredBinary binary:
                if (binary.Left is LoweredCall { Name: "isbegin_quest" } quest && binary.Operator is TokenKind.Equal or TokenKind.NotEqual && binary.Right is LoweredLiteral expected)
                {
                    output.Append("await context.GetQuestStateAsync(new QuestId("); EmitExpression(output, quest.Arguments[0]); output.Append("), cancellationToken) ").Append(Operator(binary.Operator)).Append(' ').Append(QuestState(expected.Value));
                }
                else { output.Append('('); EmitExpression(output, binary.Left); output.Append(' ').Append(Operator(binary.Operator)).Append(' '); EmitExpression(output, binary.Right); output.Append(')'); }
                break;
            case LoweredCall call: EmitCall(output, call); break;
            case LoweredIdentifier identifier: output.Append("RathenaConstants.").Append(identifier.Name); break;
        }
    }

    private static void EmitCall(StringBuilder output, LoweredCall call)
    {
        switch (call.Name)
        {
            case "select": output.Append("await context.SelectAsync(["); EmitArguments(output, call.Arguments); output.Append("], cancellationToken)"); break;
            case "strnpcinfo": output.Append("context.StrNpcInfo("); EmitArguments(output, call.Arguments); output.Append(')'); break;
            case "replacestr": output.Append("ScriptContext.ReplaceString("); EmitArguments(output, call.Arguments); output.Append(')'); break;
            case "isbegin_quest": output.Append("(int)await context.GetQuestStateAsync(new QuestId("); EmitExpression(output, call.Arguments[0]); output.Append("), cancellationToken)"); break;
        }
    }
    private static void EmitArguments(StringBuilder output, IReadOnlyList<LoweredScriptExpression> arguments) { for (var index = 0; index < arguments.Count; index++) { if (index > 0) output.Append(", "); EmitExpression(output, arguments[index]); } }
    private static string Operator(TokenKind kind) => kind switch { TokenKind.Equal => "==", TokenKind.NotEqual => "!=", TokenKind.Plus => "+", TokenKind.Less => "<", TokenKind.LessEqual => "<=", TokenKind.Greater => ">", TokenKind.GreaterEqual => ">=", _ => throw new NotSupportedException(kind.ToString()) };
    private static string QuestState(object value) => Convert.ToInt64(value, CultureInfo.InvariantCulture) switch { 0 => "CharacterQuestStatus.Absent", 1 => "CharacterQuestStatus.Active", 2 => "CharacterQuestStatus.Completed", var state => throw new NotSupportedException($"Quest state {state}") };
    private static IEnumerable<string> FindLocals(IEnumerable<LoweredScriptStatement> statements) => statements.SelectMany(statement => statement switch { LoweredAssignment assignment => [assignment.Variable], LoweredBlock block => FindLocals(block.Statements), LoweredIf conditional => FindLocals(conditional.Else is null ? [conditional.Then] : [conditional.Then, conditional.Else]), LoweredSwitch selection => FindLocals(selection.Cases.SelectMany(item => item.Statements)), _ => [] }).Distinct(StringComparer.Ordinal);
    private static string Local(string name) => "local_" + new string(name.TrimStart('.', '@').TrimEnd('$').Select(character => char.IsLetterOrDigit(character) ? character : '_').ToArray());
    private static string Escape(string value) => value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal).Replace("\r", "\\r", StringComparison.Ordinal).Replace("\n", "\\n", StringComparison.Ordinal);

    private static void EmitRegistry(StringBuilder output, GeneratedNpcMetadata metadata)
    {
        output.AppendLine("namespace Athena.Net.MapServer.World.GeneratedScripts"); output.AppendLine("{"); output.Append("internal static class ").Append(metadata.ClassName).AppendLine("Registration"); output.AppendLine("{");
        output.AppendLine("    internal static GeneratedScriptRegistration Create() =>"); output.AppendLine("        new("); output.AppendLine("            new WorldEntityDefinition(");
        output.Append("                1, \"").Append(Escape(metadata.EntityId)).AppendLine("\","); output.Append("                \"").Append(Escape(metadata.EntityKind)).AppendLine("\",");
        output.Append("                new WorldActorComponent(\"").Append(Escape(metadata.NpcName)).Append("\", \"").Append(Escape(metadata.Map)).Append("\", ").Append(metadata.X).Append(", ").Append(metadata.Y).Append(", ").Append(metadata.Direction).Append(", ").Append(metadata.Class).Append(", ").Append(metadata.EffectState).AppendLine("),");
        output.AppendLine("                [],"); output.AppendLine("                [new ScriptBehaviorDefinition("); output.Append("                    \"").Append(metadata.Trigger).Append("\", \"").Append(Escape(metadata.Map)).Append("\", ").Append(metadata.X).Append(", ").Append(metadata.Y).Append(", ").Append(metadata.RadiusX).Append(", ").Append(metadata.RadiusY).AppendLine(",");
        output.AppendLine("                    true, true,"); output.AppendLine("                    [\"Conditional\", \"QuestState\", \"Dialogue\", \"DialogueNext\", \"Selection\", \"SetQuest\", \"CompleteQuest\", \"Close\", \"Cutin\", \"VariableAssignment\", \"NpcIdentity\", \"StringReplace\", \"Warp\", \"SavePoint\"],");
        output.Append("                    \"Generated from ").Append(Escape(metadata.SourceFile)).Append(':').Append(metadata.DeclarationLine).AppendLine("\","); output.AppendLine("                    null,"); output.Append("                    ").Append(metadata.BaseNpcName is null ? "null" : $"\"{Escape(metadata.BaseNpcName)}\"").AppendLine(")],");
        output.Append("                new WorldSourceInfo(\"rAthena\", \"").Append(metadata.SourceCommit).Append("\", \"").Append(Escape(metadata.SourceFile)).Append("\", ").Append(metadata.DeclarationLine).AppendLine(")),");
        output.Append("            \"").Append(metadata.Trigger).AppendLine("\","); output.Append("            static () => new ").Append(metadata.Namespace).Append('.').Append(metadata.ClassName).AppendLine("());"); output.AppendLine("}"); output.AppendLine("}");
    }
}
