using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

namespace Athena.WorldCompiler.Generation;

internal static partial class ProgressionDataCompiler
{
    internal static string Generate(string jobExperienceYaml, string jobBasePointsYaml, string jobStatsYaml, string statPointYaml, string commit)
    {
        var experienceBlocks = JobBlocks(jobExperienceYaml);
        var noviceBase = experienceBlocks.Single(block => HasJob(block, "Novice") && block.Contains("    MaxBaseLevel:", StringComparison.Ordinal));
        var noviceJob = experienceBlocks.Single(block => HasJob(block, "Novice") && block.Contains("    MaxJobLevel: 10", StringComparison.Ordinal));
        var basePointBlocks = JobBlocks(jobBasePointsYaml);
        var noviceHp = basePointBlocks.Single(block => HasJob(block, "Novice") && block.Contains("    BaseHp:", StringComparison.Ordinal));
        var noviceSp = basePointBlocks.Single(block => HasJob(block, "Novice") && block.Contains("    BaseSp:", StringComparison.Ordinal));

        var maxBaseLevel = Scalar(noviceBase, "MaxBaseLevel");
        var maxJobLevel = Scalar(noviceJob, "MaxJobLevel");
        var baseExperience = LevelValues(noviceBase, "BaseExp", "Exp", maxBaseLevel);
        var jobExperience = LevelValues(noviceJob, "JobExp", "Exp", maxJobLevel);
        var baseHp = LevelValues(noviceHp, "BaseHp", "Hp", maxBaseLevel);
        var baseSp = LevelValues(noviceSp, "BaseSp", "Sp", maxBaseLevel);
        var statPoints = StatPointValues(statPointYaml, maxBaseLevel);
        var noviceStats = JobBlocks(jobStatsYaml).Single(block => HasJob(block, "Novice"));
        var vitalityBonuses = CumulativeJobBonus(noviceStats, "Vit", maxJobLevel);
        var intelligenceBonuses = CumulativeJobBonus(noviceStats, "Int", maxJobLevel);

        var output = new StringBuilder()
            .AppendLine("// <auto-generated>")
            .AppendLine("// Generated by Athena.WorldCompiler.")
            .AppendLine("// Sources: legacy/rathena/db/re/job_exp.yml, job_basepoints.yml, job_stats.yml, statpoint.yml")
            .Append("// rAthena commit: ").AppendLine(commit)
            .AppendLine("// Do not edit this file directly.")
            .AppendLine("// </auto-generated>")
            .AppendLine("namespace Athena.Net.MapServer.Generated.Progression;")
            .AppendLine()
            .AppendLine("internal static class GeneratedNoviceProgression")
            .AppendLine("{")
            .AppendLine("    internal const ushort JobClass = 0;")
            .Append("    internal const ushort MaxBaseLevel = ").Append(maxBaseLevel).AppendLine(";")
            .Append("    internal const ushort MaxJobLevel = ").Append(maxJobLevel).AppendLine(";");
        Emit(output, "BaseExperienceToNext", "ulong", baseExperience);
        Emit(output, "JobExperienceToNext", "ulong", jobExperience);
        Emit(output, "BaseHp", "uint", baseHp);
        Emit(output, "BaseSp", "uint", baseSp);
        Emit(output, "CumulativeStatPoints", "uint", statPoints);
        Emit(output, "JobVitalityBonus", "uint", vitalityBonuses);
        Emit(output, "JobIntelligenceBonus", "uint", intelligenceBonuses);
        return output.AppendLine("}").ToString();
    }

    private static string[] JobBlocks(string yaml) => JobBlockRegex().Matches(yaml).Select(match => match.Value).ToArray();
    private static bool HasJob(string block, string job) => block.Contains($"      {job}: true", StringComparison.Ordinal);
    private static ushort Scalar(string block, string name) => ushort.Parse(ScalarRegex(name).Match(block).Groups[1].Value, CultureInfo.InvariantCulture);

    private static ulong[] LevelValues(string source, string section, string valueName, int maxLevel)
    {
        var sectionMatch = SectionRegex(section).Match(source);
        if (!sectionMatch.Success) throw new ArgumentException($"Pinned progression section '{section}' was not found.");
        var result = new ulong[maxLevel + 1];
        foreach (Match match in LevelValueRegex(valueName).Matches(sectionMatch.Groups[1].Value))
        {
            var level = int.Parse(match.Groups[1].Value, CultureInfo.InvariantCulture);
            if (level <= maxLevel) result[level] = ulong.Parse(match.Groups[2].Value, CultureInfo.InvariantCulture);
        }
        if (result.Skip(1).Any(value => value == 0)) throw new ArgumentException($"Pinned progression section '{section}' has missing levels.");
        return result;
    }

    private static ulong[] StatPointValues(string source, int maxLevel)
    {
        var result = new ulong[maxLevel + 1];
        foreach (Match match in StatPointRegex().Matches(source))
        {
            var level = int.Parse(match.Groups[1].Value, CultureInfo.InvariantCulture);
            if (level <= maxLevel) result[level] = ulong.Parse(match.Groups[2].Value, CultureInfo.InvariantCulture);
        }
        if (result.Skip(1).Any(value => value == 0)) throw new ArgumentException("Pinned statpoint data has missing levels.");
        return result;
    }

    private static ulong[] CumulativeJobBonus(string block, string stat, int maxLevel)
    {
        var result = new ulong[maxLevel + 1];
        foreach (Match entry in BonusEntryRegex().Matches(block))
        {
            var level = int.Parse(entry.Groups[1].Value, CultureInfo.InvariantCulture);
            var statMatch = Regex.Match(entry.Groups[2].Value, $"(?m)^        {stat}: (\\d+)$", RegexOptions.CultureInvariant);
            if (level <= maxLevel && statMatch.Success) result[level] += ulong.Parse(statMatch.Groups[1].Value, CultureInfo.InvariantCulture);
        }
        for (var level = 1; level <= maxLevel; level++) result[level] += result[level - 1];
        return result;
    }

    private static void Emit(StringBuilder output, string name, string type, IReadOnlyList<ulong> values) =>
        output.Append("    internal static readonly ").Append(type).Append("[] ").Append(name).Append(" = [")
            .Append(string.Join(", ", values.Select(value => value.ToString(CultureInfo.InvariantCulture))))
            .AppendLine("];");

    [GeneratedRegex("(?ms)^  - Jobs:\\r?\\n.*?(?=^  - Jobs:|\\z)")]
    private static partial Regex JobBlockRegex();
    [GeneratedRegex("(?m)^  - Level: (\\d+)\\r?\\n    Points: (\\d+)$")]
    private static partial Regex StatPointRegex();
    [GeneratedRegex("(?ms)^      - Level: (\\d+)\\r?\\n(.*?)(?=^      - Level:|^  - Jobs:|\\z)")]
    private static partial Regex BonusEntryRegex();
    private static Regex ScalarRegex(string name) => new($"(?m)^    {Regex.Escape(name)}: (\\d+)$", RegexOptions.CultureInvariant);
    private static Regex SectionRegex(string name) => new($"(?ms)^    {Regex.Escape(name)}:\\r?\\n(?<rows>.*?)(?=^    [A-Za-z]|^  - Jobs:|\\z)", RegexOptions.CultureInvariant);
    private static Regex LevelValueRegex(string name) => new($"(?m)^      - Level: (\\d+)\\r?\\n        {Regex.Escape(name)}: (\\d+)$", RegexOptions.CultureInvariant);
}
