using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

namespace Athena.WorldCompiler.Generation;

// Compiles the pinned rAthena quest_db.yml `Drops:` block for one quest.
// Mirrors quest_read_db's own field semantics (src/map/quest.cpp
// QuestDatabase::parseBodyNode): an omitted `Count` defaults to 1, `Rate` is
// out of 10000 (rnd_chance(rate, 10000)), and `Mob` is an Aegis name resolved
// against mob_db.yml, not a numeric id in the YAML itself. This intentionally
// does not model quest_db.yml `Targets:` (kill-count objectives) - quest
// 21008 in the pinned source has no Targets block, only Drops, and this
// compiler must not silently invent one.
internal static class QuestDropDataCompiler
{
    internal sealed record QuestDropData(uint QuestId, string Title, string MobAegisName, int MobId, string ItemAegisName, int ItemId, int Count, int Rate);

    internal static QuestDropData ReadSingleDrop(string questDbYaml, uint questId, string mobDbYaml, string itemDbYaml)
    {
        var marker = $"  - Id: {questId.ToString(CultureInfo.InvariantCulture)}\n";
        var start = questDbYaml.IndexOf(marker, StringComparison.Ordinal);
        if (start < 0) throw new ArgumentException($"Quest Id {questId} was not found in the pinned quest_db.yml.");
        var next = questDbYaml.IndexOf("\n  - Id: ", start + marker.Length, StringComparison.Ordinal);
        var block = next >= 0 ? questDbYaml[start..(next + 1)] : questDbYaml[start..];

        if (block.Contains("Targets:", StringComparison.Ordinal))
        {
            throw new ArgumentException($"Quest {questId} has a Targets block in the pinned source; QuestDropDataCompiler only supports drop-only quests and must not silently ignore kill-count objectives.");
        }

        var titleMatch = Regex.Match(block, @"^    Title: (.+)$", RegexOptions.Multiline);
        var title = titleMatch.Success ? titleMatch.Groups[1].Value : string.Empty;

        var dropsSection = Regex.Match(block, @"    Drops:\n(.+)", RegexOptions.Singleline);
        if (!dropsSection.Success) throw new ArgumentException($"Quest {questId} has no Drops block in the pinned source.");
        var dropsText = dropsSection.Groups[1].Value;

        var mobName = Regex.Match(dropsText, @"^      - Mob: (.+)$", RegexOptions.Multiline);
        var itemName = Regex.Match(dropsText, @"^        Item: (.+)$", RegexOptions.Multiline);
        var rateMatch = Regex.Match(dropsText, @"^        Rate: (\d+)$", RegexOptions.Multiline);
        var countMatch = Regex.Match(dropsText, @"^        Count: (\d+)$", RegexOptions.Multiline);
        if (!mobName.Success || !itemName.Success || !rateMatch.Success)
        {
            throw new ArgumentException($"Quest {questId}'s Drops block is missing Mob/Item/Rate.");
        }

        var mobId = ResolveMobId(mobDbYaml, mobName.Groups[1].Value);
        var itemId = ResolveItemId(itemDbYaml, itemName.Groups[1].Value);
        // quest.cpp: `if (!this->nodeExists(dropNode, "Count")) { if (!targetExists) target->count = 1; }`
        var count = countMatch.Success ? int.Parse(countMatch.Groups[1].Value, CultureInfo.InvariantCulture) : 1;
        var rate = int.Parse(rateMatch.Groups[1].Value, CultureInfo.InvariantCulture);

        return new QuestDropData(questId, title, mobName.Groups[1].Value, mobId, itemName.Groups[1].Value, itemId, count, rate);
    }

    private static int ResolveMobId(string mobDbYaml, string aegisName)
    {
        var match = Regex.Match(mobDbYaml, $@"  - Id: (\d+)\n    AegisName: {Regex.Escape(aegisName)}$", RegexOptions.Multiline);
        if (!match.Success) throw new ArgumentException($"Mob AegisName '{aegisName}' was not found in the pinned mob_db.yml.");
        return int.Parse(match.Groups[1].Value, CultureInfo.InvariantCulture);
    }

    private static int ResolveItemId(string itemDbYaml, string aegisName)
    {
        var match = Regex.Match(itemDbYaml, $@"  - Id: (\d+)\n    AegisName: {Regex.Escape(aegisName)}$", RegexOptions.Multiline);
        if (!match.Success) throw new ArgumentException($"Item AegisName '{aegisName}' was not found in the pinned item_db.");
        return int.Parse(match.Groups[1].Value, CultureInfo.InvariantCulture);
    }

    internal static string Generate(QuestDropData drop, string commit, string sourceFile, int sourceLine)
    {
        return new StringBuilder()
            .AppendLine("// <auto-generated>")
            .AppendLine("// Generated by Athena.WorldCompiler.")
            .Append("// Source: ").Append(sourceFile).Append(':').Append(sourceLine.ToString(CultureInfo.InvariantCulture)).AppendLine()
            .Append("// rAthena commit: ").AppendLine(commit)
            .AppendLine("// Do not edit this file directly.")
            .AppendLine("// </auto-generated>")
            .AppendLine("using Athena.Net.MapServer.World;")
            .AppendLine()
            // Quest/game data ("quest <id>: killing mob X may produce item Y") - not world/
            // placement data, so this does not live under Generated.World.Izlude.Academy.
            .AppendLine("namespace Athena.Net.MapServer.Generated.GameData.Quests;")
            .AppendLine()
            .AppendLine("internal static class GeneratedQuestDrops")
            .AppendLine("{")
            .AppendLine("    // Quest 21008 ('The first battle') in the pinned quest_db.yml has ONLY a")
            .AppendLine("    // Drops rule, no Targets kill-count objectives. Progression happens by")
            .AppendLine("    // acquiring the dropped item, not by incrementing a kill counter.")
            .Append("    internal static readonly QuestDropRule[] All = [ new(QuestId: ").Append(drop.QuestId)
            .Append(", MobId: ").Append(drop.MobId)
            .Append(", ItemId: ").Append(drop.ItemId)
            .Append(", Count: ").Append(drop.Count)
            .Append(", Rate: ").Append(drop.Rate)
            .Append(", Source: new WorldSourceInfo(\"rAthena\", \"").Append(commit).Append("\", \"").Append(sourceFile).Append("\", ").Append(sourceLine).AppendLine(")) ];")
            .AppendLine("}")
            .ToString();
    }
}
