using System.IO.Compression;
using System.Text;
using Athena.Rathena.Data;
using Athena.WorldCompiler.Generation;

internal static partial class WorldDataImporterCli
{
    private const string MapRegistryFile = "GeneratedMapRegistry.cs";
    private const string WarpRegistryFile = "GeneratedWarpRegistry.cs";

    private static async Task<int> GenerateMapsAsync(string[] args)
    {
        var options = CliOptions.Parse(args);
        var root = Path.GetFullPath(options.Required("rathena-root"));
        var output = Path.GetFullPath(options.Required("output"));
        var commit = options.Optional("rathena-commit") ?? ReadPinnedCommit(root);
        var basePath = Path.Combine(root, "db/map_cache.dat");
        var renewalPath = Path.Combine(root, "db/re/map_cache.dat");
        var importPath = Path.Combine(root, "db/import/map_cache.dat");
        var maps = RathenaMapCacheLayers.Merge(
            await File.ReadAllBytesAsync(basePath),
            File.Exists(renewalPath) ? await File.ReadAllBytesAsync(renewalPath) : null,
            File.Exists(importPath) ? await File.ReadAllBytesAsync(importPath) : null);

        Directory.CreateDirectory(output);
        DeleteOwned(output, path => Path.GetFileName(path) == MapRegistryFile || Path.GetFileName(path).EndsWith("Map.cs", StringComparison.Ordinal), "Generated by Athena.WorldCompiler map generator.");
        var usedFolders = new HashSet<string>(StringComparer.Ordinal);
        var placements = maps.Select(map => (Map: map, Placement: MapModuleNaming.Resolve(map.Entry.Name, usedFolders))).ToArray();
        var expressions = new List<string>();
        foreach (var group in placements.GroupBy(item => item.Placement.FolderPath, StringComparer.Ordinal).OrderBy(item => item.Key, StringComparer.Ordinal))
        {
            var first = group.First().Placement;
            var source = EmitMapModule(group.OrderBy(item => item.Map.Entry.Name, StringComparer.Ordinal).ToArray(), first, commit);
            var directory = Path.Combine(output, first.FolderPath.Replace('/', Path.DirectorySeparatorChar));
            Directory.CreateDirectory(directory);
            await File.WriteAllTextAsync(Path.Combine(directory, first.ClassName + "Map.cs"), source, new UTF8Encoding(false));
            expressions.Add(first.Namespace + "." + first.ClassName + "Map.All");
        }
        await File.WriteAllTextAsync(Path.Combine(output, MapRegistryFile), EmitMapRegistry(expressions, commit), new UTF8Encoding(false));
        Console.WriteLine($"Maps discovered: {maps.Count}");
        Console.WriteLine($"Maps generated:  {maps.Count}");
        Console.WriteLine($"Generated map modules: {expressions.Count}");
        return 0;
    }

    private static async Task<int> GenerateWarpsAsync(string[] args)
    {
        var options = CliOptions.Parse(args);
        var root = Path.GetFullPath(options.Required("rathena-root"));
        var output = Path.GetFullPath(options.Required("output"));
        var commit = options.Optional("rathena-commit") ?? ReadPinnedCommit(root);
        var npcRoot = Path.Combine(root, "npc");
        var declarations = RathenaSourceParser.Parse([npcRoot]).Where(item => item.Directive == "warp")
            .OrderBy(item => item.Source.File, StringComparer.Ordinal).ThenBy(item => item.Source.Line).ToArray();
        var conversion = WorldEntityConverter.ConvertDeclarativeWarps([npcRoot]);
        if (conversion.Unsupported.Count > 0)
            throw new ArgumentException("generate-warps cannot represent: " + string.Join("; ", conversion.Unsupported.Select(item => $"{item.File}:{item.Line} {item.Reason}")));
        var converted = conversion.Entities.Where(item => declarations.Any(source => source.Source.File == item.Source.File && source.Source.Line == item.Source.Line)).ToArray();
        var byIdentity = converted.ToDictionary(item => (item.Source.File, item.Source.Line));
        var missing = declarations.Where(item => !byIdentity.ContainsKey((item.Source.File, item.Source.Line))).ToArray();
        if (missing.Length > 0) throw new ArgumentException("generate-warps did not convert: " + string.Join(", ", missing.Select(item => $"{item.Source.File}:{item.Source.Line}")));

        var mapNames = (await LoadEffectiveMaps(root)).Select(item => item.Entry.Name).ToHashSet(StringComparer.OrdinalIgnoreCase);
        var warps = declarations.Select(source => byIdentity[(source.Source.File, source.Source.Line)]).ToArray();
        var unresolvedSources = warps.Where(item => !mapNames.Contains(item.Triggers[0].Map)).ToArray();
        var unresolvedDestinations = warps.Where(item => !mapNames.Contains(((WarpAction)item.Triggers[0].Actions.Single()).Map)).ToArray();
        if (unresolvedSources.Length > 0 || unresolvedDestinations.Length > 0)
            throw new ArgumentException($"generate-warps unresolved maps: sources={unresolvedSources.Length}, destinations={unresolvedDestinations.Length}.");

        Directory.CreateDirectory(output);
        DeleteOwned(output, path => Path.GetFileName(path) == WarpRegistryFile || Path.GetFileName(path).EndsWith("Warps.cs", StringComparison.Ordinal), "Generated by Athena.WorldCompiler warp generator.");
        var usedFolders = new HashSet<string>(StringComparer.Ordinal);
        var placementByMap = mapNames.Order(StringComparer.Ordinal).ToDictionary(map => map, map => MapModuleNaming.ResolveWarp(map, usedFolders), StringComparer.Ordinal);
        var expressions = new List<string>();
        foreach (var group in warps.GroupBy(item => placementByMap[item.Triggers[0].Map].FolderPath, StringComparer.Ordinal).OrderBy(item => item.Key, StringComparer.Ordinal))
        {
            var first = placementByMap[group.First().Triggers[0].Map];
            var source = EmitWarpModule(group.OrderBy(item => item.Source.File, StringComparer.Ordinal).ThenBy(item => item.Source.Line).ToArray(), first, commit);
            var directory = Path.Combine(output, first.FolderPath.Replace('/', Path.DirectorySeparatorChar));
            Directory.CreateDirectory(directory);
            await File.WriteAllTextAsync(Path.Combine(directory, first.ClassName + "Warps.cs"), source, new UTF8Encoding(false));
            expressions.Add(first.Namespace + "." + first.ClassName + "Warps.All");
        }
        await File.WriteAllTextAsync(Path.Combine(output, WarpRegistryFile), EmitWarpRegistry(expressions, commit), new UTF8Encoding(false));
        Console.WriteLine($"Warp declarations discovered: {declarations.Length}");
        Console.WriteLine($"Warps generated:              {warps.Length}");
        Console.WriteLine($"Source maps resolved:         {warps.Length} / {warps.Length}");
        Console.WriteLine($"Destination maps resolved:    {warps.Length} / {warps.Length}");
        return 0;
    }

    private static async Task<IReadOnlyList<RathenaMapCacheLayers.ResolvedMap>> LoadEffectiveMaps(string root)
    {
        var basePath = Path.Combine(root, "db/map_cache.dat");
        var renewalPath = Path.Combine(root, "db/re/map_cache.dat");
        var importPath = Path.Combine(root, "db/import/map_cache.dat");
        return RathenaMapCacheLayers.Merge(await File.ReadAllBytesAsync(basePath), File.Exists(renewalPath) ? await File.ReadAllBytesAsync(renewalPath) : null, File.Exists(importPath) ? await File.ReadAllBytesAsync(importPath) : null);
    }

    private static string EmitMapModule(IReadOnlyList<(RathenaMapCacheLayers.ResolvedMap Map, MapModulePlacement Placement)> maps, MapModulePlacement placement, string commit)
    {
        var b = Header("map", commit).AppendLine("using Athena.Net.MapServer.World;").AppendLine().Append("namespace ").Append(placement.Namespace).AppendLine(";").AppendLine()
            .Append("internal static class ").Append(placement.ClassName).AppendLine("Map").AppendLine("{");
        foreach (var item in maps)
        {
            var sourceFile = item.Map.Source switch { RathenaMapCacheLayers.Provenance.ImportOverlay => "legacy/rathena/db/import/map_cache.dat", RathenaMapCacheLayers.Provenance.RenewalOverlay => "legacy/rathena/db/re/map_cache.dat", _ => "legacy/rathena/db/map_cache.dat" };
            b.Append("    internal static readonly GeneratedMapDefinition ").Append(item.Placement.ArrayName).Append(" = new(\"").Append(E(item.Map.Entry.Name)).Append("\", ")
                .Append(item.Map.Entry.Width).Append(", ").Append(item.Map.Entry.Height).Append(", \"").Append(Compress(item.Map.Entry.RawCells)).Append("\", \"")
                .Append(item.Map.Source).Append("\", new(\"rAthena\", \"").Append(E(commit)).Append("\", \"").Append(sourceFile).AppendLine("\", 0));");
        }
        b.AppendLine().AppendLine("    internal static readonly GeneratedMapDefinition[] All =")
            .Append("        [").Append(string.Join(", ", maps.Select(item => item.Placement.ArrayName))).AppendLine("];").AppendLine("}");
        return b.ToString();
    }

    private static string EmitWarpModule(IReadOnlyList<WorldEntityDefinition> warps, MapModulePlacement placement, string commit)
    {
        var b = Header("warp", commit).AppendLine("using Athena.Net.MapServer.World;").AppendLine().Append("namespace ").Append(placement.Namespace).AppendLine(";").AppendLine()
            .Append("internal static class ").Append(placement.ClassName).AppendLine("Warps").AppendLine("{").AppendLine("    internal static readonly WarpDefinition[] All =").AppendLine("    [");
        foreach (var entity in warps)
        {
            var trigger = entity.Triggers.Single(); var destination = (WarpAction)trigger.Actions.Single();
            b.Append("        new(\"").Append(E(entity.Actor!.Name)).Append("\", \"").Append(E(trigger.Map)).Append("\", ").Append(trigger.X).Append(", ").Append(trigger.Y).Append(", ")
                .Append(trigger.RadiusX).Append(", ").Append(trigger.RadiusY).Append(", \"").Append(E(destination.Map)).Append("\", ").Append(destination.X).Append(", ").Append(destination.Y)
                .Append(", true, new(\"rAthena\", \"").Append(E(commit)).Append("\", \"").Append(E(entity.Source.File)).Append("\", ").Append(entity.Source.Line).AppendLine(")),");
        }
        return b.AppendLine("    ];").AppendLine("}").ToString();
    }

    private static string EmitMapRegistry(IReadOnlyList<string> expressions, string commit) => Header("map", commit).AppendLine("using System.Collections.Frozen;").AppendLine("using Athena.Net.MapServer.World;").AppendLine()
        .AppendLine("namespace Athena.Net.MapServer.Generated.World;").AppendLine().AppendLine("internal static class GeneratedMapRegistry").AppendLine("{")
        .Append("    internal static readonly GeneratedMapDefinition[] All = [.. ").Append(string.Join(", .. ", expressions.Order(StringComparer.Ordinal))).AppendLine("];")
        .AppendLine("    private static readonly FrozenDictionary<string, GeneratedMapDefinition> ByName = All.ToFrozenDictionary(map => map.Name, StringComparer.OrdinalIgnoreCase);")
        .AppendLine("    internal static int Count => All.Length;").AppendLine("    internal static bool TryGet(string name, out GeneratedMapDefinition map) => ByName.TryGetValue(MapName.NormalizeWorld(name), out map!);")
        .AppendLine("    internal static GeneratedMapDefinition Get(string name) => ByName[MapName.NormalizeWorld(name)];").AppendLine("}").ToString();

    private static string EmitWarpRegistry(IReadOnlyList<string> expressions, string commit) => Header("warp", commit).AppendLine("using System.Collections.Frozen;").AppendLine("using Athena.Net.MapServer.World;").AppendLine()
        .AppendLine("namespace Athena.Net.MapServer.Generated.World;").AppendLine().AppendLine("internal static class GeneratedWarpRegistry").AppendLine("{")
        .Append("    internal static readonly WarpDefinition[] All = [.. ").Append(string.Join(", .. ", expressions.Order(StringComparer.Ordinal))).AppendLine("];")
        .AppendLine("    private static readonly FrozenDictionary<string, WarpDefinition[]> ByMap = All.GroupBy(warp => warp.SourceMap, StringComparer.OrdinalIgnoreCase).ToFrozenDictionary(group => group.Key, group => group.ToArray(), StringComparer.OrdinalIgnoreCase);")
        .AppendLine("    internal static int Count => All.Length;").AppendLine("    internal static bool TryGetForMap(string map, out IReadOnlyList<WarpDefinition> warps) { if (ByMap.TryGetValue(MapName.NormalizeWorld(map), out var found)) { warps = found; return true; } warps = []; return false; }")
        .AppendLine("    internal static IReadOnlyList<WarpDefinition> GetForMap(string map) => ByMap.TryGetValue(MapName.NormalizeWorld(map), out var found) ? found : [];").AppendLine("}").ToString();

    private static StringBuilder Header(string domain, string commit) => new StringBuilder("// <auto-generated>\n// Generated by Athena.WorldCompiler ").Append(domain).Append(" generator.\n// rAthena commit: ").Append(commit).Append("\n// Do not edit this file directly.\n// </auto-generated>\n");
    private static string Compress(byte[] raw) { using var output = new MemoryStream(); using (var zlib = new ZLibStream(output, CompressionLevel.SmallestSize, true)) zlib.Write(raw); return Convert.ToBase64String(output.ToArray()); }
    private static string E(string value) => value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
    private static void DeleteOwned(string root, Func<string, bool> nameMatch, string marker)
    {
        foreach (var path in Directory.EnumerateFiles(root, "*.cs", SearchOption.AllDirectories).Where(nameMatch))
            if (File.ReadLines(path).Take(5).Any(line => line == "// <auto-generated>") &&
                File.ReadLines(path).Take(5).Any(line => line.Contains(marker, StringComparison.Ordinal) || line.Contains("Generated by Athena.WorldCompiler from pinned rAthena.", StringComparison.Ordinal)))
                File.Delete(path);
    }
}
