// <auto-generated />
using System;
using Athena.Net.LoginServer.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoginServer.Migrations
{
    [DbContext(typeof(LoginDbContext))]
    [Migration("20260927142515_DropLoginAccountTable")]
    partial class DropLoginAccountTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Athena.Net.LoginServer.Db.Entities.AccountRegNum", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("key");

                    b.Property<long>("Index")
                        .HasColumnType("bigint")
                        .HasColumnName("index");

                    b.Property<long>("Value")
                        .HasColumnType("bigint")
                        .HasColumnName("value");

                    b.HasKey("AccountId", "Key", "Index");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("account_id");

                    b.ToTable("global_acc_reg_num", (string)null);
                });

            modelBuilder.Entity("Athena.Net.LoginServer.Db.Entities.AccountRegStr", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("key");

                    b.Property<long>("Index")
                        .HasColumnType("bigint")
                        .HasColumnName("index");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasColumnName("value");

                    b.HasKey("AccountId", "Key", "Index");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("account_id");

                    b.ToTable("global_acc_reg_str", (string)null);
                });

            modelBuilder.Entity("Athena.Net.LoginServer.Db.Entities.IpBanEntry", b =>
                {
                    b.Property<string>("List")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValue("")
                        .HasColumnName("list");

                    b.Property<DateTime>("BanTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("btime");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("")
                        .HasColumnName("reason");

                    b.Property<DateTime>("ReleaseTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("rtime");

                    b.HasKey("List", "BanTime");

                    b.ToTable("ipbanlist", (string)null);
                });

            modelBuilder.Entity("Athena.Net.LoginServer.Db.Entities.LoginLogEntry", b =>
                {
                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("ip");

                    b.Property<string>("Log")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("log");

                    b.Property<byte>("ResultCode")
                        .HasColumnType("tinyint")
                        .HasColumnName("rcode");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2")
                        .HasColumnName("time");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(23)
                        .HasColumnType("nvarchar(23)")
                        .HasColumnName("user");

                    b.HasIndex("Ip")
                        .HasDatabaseName("ip");

                    b.ToTable("loginlog", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
