// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Athena.Net.LoginServer.Db;

#nullable disable

namespace LoginServer.Migrations
{
    [DbContext(typeof(LoginDbContext))]
    [Migration("20260117180129_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Athena.Net.LoginServer.Db.Entities.AccountRegNum", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("key");

                    b.Property<long>("Index")
                        .HasColumnType("bigint")
                        .HasColumnName("index");

                    b.Property<long>("Value")
                        .HasColumnType("bigint")
                        .HasColumnName("value");

                    b.HasKey("AccountId", "Key", "Index");

                    b.ToTable("global_acc_reg_num", (string)null);
                });

            modelBuilder.Entity("Athena.Net.LoginServer.Db.Entities.AccountRegStr", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("key");

                    b.Property<long>("Index")
                        .HasColumnType("bigint")
                        .HasColumnName("index");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasColumnName("value");

                    b.HasKey("AccountId", "Key", "Index");

                    b.ToTable("global_acc_reg_str", (string)null);
                });

            modelBuilder.Entity("Athena.Net.LoginServer.Db.Entities.IpBanEntry", b =>
                {
                    b.Property<string>("List")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("list");

                    b.Property<DateTime>("BanTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("btime");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("ReleaseTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("rtime");

                    b.HasKey("List", "BanTime");

                    b.ToTable("ipbanlist", (string)null);
                });

            modelBuilder.Entity("Athena.Net.LoginServer.Db.Entities.LoginAccount", b =>
                {
                    b.Property<long>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AccountId"));

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("date")
                        .HasColumnName("birthdate");

                    b.Property<byte>("CharacterSlots")
                        .HasColumnType("tinyint")
                        .HasColumnName("character_slots");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(39)
                        .HasColumnType("nvarchar(39)")
                        .HasColumnName("email");

                    b.Property<long>("ExpirationTime")
                        .HasColumnType("bigint")
                        .HasColumnName("expiration_time");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<string>("LastIp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("last_ip");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("lastlogin");

                    b.Property<int>("LoginCount")
                        .HasColumnType("int")
                        .HasColumnName("logincount");

                    b.Property<int>("OldGroup")
                        .HasColumnType("int")
                        .HasColumnName("old_group");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("pincode");

                    b.Property<long>("PincodeChange")
                        .HasColumnType("bigint")
                        .HasColumnName("pincode_change");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("sex");

                    b.Property<long>("State")
                        .HasColumnType("bigint")
                        .HasColumnName("state");

                    b.Property<long>("UnbanTime")
                        .HasColumnType("bigint")
                        .HasColumnName("unban_time");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(23)
                        .HasColumnType("nvarchar(23)")
                        .HasColumnName("userid");

                    b.Property<string>("UserPass")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("user_pass");

                    b.Property<long>("VipTime")
                        .HasColumnType("bigint")
                        .HasColumnName("vip_time");

                    b.Property<string>("WebAuthToken")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)")
                        .HasColumnName("web_auth_token");

                    b.Property<bool>("WebAuthTokenEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("web_auth_token_enabled");

                    b.HasKey("AccountId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("name");

                    b.HasIndex("WebAuthToken")
                        .IsUnique()
                        .HasDatabaseName("web_auth_token_key")
                        .HasFilter("[web_auth_token] IS NOT NULL");

                    b.ToTable("login", (string)null);
                });

            modelBuilder.Entity("Athena.Net.LoginServer.Db.Entities.LoginLogEntry", b =>
                {
                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2")
                        .HasColumnName("time");

                    b.Property<string>("Ip")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("ip");

                    b.Property<string>("User")
                        .HasMaxLength(23)
                        .HasColumnType("nvarchar(23)")
                        .HasColumnName("user");

                    b.Property<byte>("ResultCode")
                        .HasColumnType("tinyint")
                        .HasColumnName("rcode");

                    b.Property<string>("Log")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("log");

                    b.HasKey("Time", "Ip", "User", "ResultCode", "Log");

                    b.ToTable("loginlog", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
