using System.Buffers.Binary;
namespace Athena.Net.CharServer.Net;
internal static class MapCharacterGameplayStateProtocol
{
    internal const int GetRequestLength=10,StateLength=68,UpdateRequestLength=142,ResponseLength=75;
    internal static bool TryParseGet(ReadOnlySpan<byte> p,out uint a,out uint c){a=0;c=0;if(p.Length!=GetRequestLength||BinaryPrimitives.ReadInt16LittleEndian(p)!=PacketConstants.MapGameplayStateGetRequest)return false;a=BinaryPrimitives.ReadUInt32LittleEndian(p[2..]);c=BinaryPrimitives.ReadUInt32LittleEndian(p[6..]);return true;}
    internal static bool TryParseUpdate(ReadOnlySpan<byte> p,out uint a,out CharacterGameplayStateDto e,out CharacterGameplayStateDto u){a=0;e=null!;u=null!;if(p.Length!=UpdateRequestLength||BinaryPrimitives.ReadInt16LittleEndian(p)!=PacketConstants.MapGameplayStateUpdateRequest)return false;a=BinaryPrimitives.ReadUInt32LittleEndian(p[2..]);e=Read(p.Slice(6,StateLength));u=Read(p.Slice(74,StateLength));return true;}
    internal static byte[] BuildResponse(short type,byte result,uint charId,CharacterGameplayStateDto? state){var p=new byte[ResponseLength];BinaryPrimitives.WriteInt16LittleEndian(p,type);p[2]=result;BinaryPrimitives.WriteUInt32LittleEndian(p.AsSpan(3),charId);if(state is not null)Write(p.AsSpan(7),state);return p;}
    internal static CharacterGameplayStateDto Read(ReadOnlySpan<byte>s)=>new(BinaryPrimitives.ReadUInt32LittleEndian(s),BinaryPrimitives.ReadUInt64LittleEndian(s[4..]),BinaryPrimitives.ReadUInt16LittleEndian(s[12..]),BinaryPrimitives.ReadUInt16LittleEndian(s[14..]),BinaryPrimitives.ReadUInt64LittleEndian(s[16..]),BinaryPrimitives.ReadUInt64LittleEndian(s[24..]),BinaryPrimitives.ReadUInt32LittleEndian(s[32..]),BinaryPrimitives.ReadUInt32LittleEndian(s[36..]),BinaryPrimitives.ReadUInt32LittleEndian(s[40..]),BinaryPrimitives.ReadUInt32LittleEndian(s[44..]),BinaryPrimitives.ReadUInt32LittleEndian(s[48..]),BinaryPrimitives.ReadUInt32LittleEndian(s[52..]),BinaryPrimitives.ReadUInt16LittleEndian(s[56..]),BinaryPrimitives.ReadUInt16LittleEndian(s[58..]),BinaryPrimitives.ReadUInt16LittleEndian(s[60..]),BinaryPrimitives.ReadUInt16LittleEndian(s[62..]),BinaryPrimitives.ReadUInt16LittleEndian(s[64..]),BinaryPrimitives.ReadUInt16LittleEndian(s[66..]));
    internal static void Write(Span<byte>s,CharacterGameplayStateDto v){BinaryPrimitives.WriteUInt32LittleEndian(s,v.CharacterId);BinaryPrimitives.WriteUInt64LittleEndian(s[4..],v.Version);BinaryPrimitives.WriteUInt16LittleEndian(s[12..],v.BaseLevel);BinaryPrimitives.WriteUInt16LittleEndian(s[14..],v.JobLevel);BinaryPrimitives.WriteUInt64LittleEndian(s[16..],v.BaseExperience);BinaryPrimitives.WriteUInt64LittleEndian(s[24..],v.JobExperience);BinaryPrimitives.WriteUInt32LittleEndian(s[32..],v.CurrentHp);BinaryPrimitives.WriteUInt32LittleEndian(s[36..],v.CurrentSp);BinaryPrimitives.WriteUInt32LittleEndian(s[40..],v.MaxHp);BinaryPrimitives.WriteUInt32LittleEndian(s[44..],v.MaxSp);BinaryPrimitives.WriteUInt32LittleEndian(s[48..],v.StatPoints);BinaryPrimitives.WriteUInt32LittleEndian(s[52..],v.SkillPoints);BinaryPrimitives.WriteUInt16LittleEndian(s[56..],v.Strength);BinaryPrimitives.WriteUInt16LittleEndian(s[58..],v.Agility);BinaryPrimitives.WriteUInt16LittleEndian(s[60..],v.Vitality);BinaryPrimitives.WriteUInt16LittleEndian(s[62..],v.Intelligence);BinaryPrimitives.WriteUInt16LittleEndian(s[64..],v.Dexterity);BinaryPrimitives.WriteUInt16LittleEndian(s[66..],v.Luck);}
}
