// <auto-generated />
using System;
using Athena.Net.CharServer.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CharServer.Migrations
{
    [DbContext(typeof(CharDbContext))]
    [Migration("20260823171957_InitialCharSchema")]
    partial class InitialCharSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Athena.Net.CharServer.Db.Entities.CharCharacter", b =>
                {
                    b.Property<long>("CharId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("char_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CharId"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<int>("Agi")
                        .HasColumnType("int")
                        .HasColumnName("agi");

                    b.Property<long>("Ap")
                        .HasColumnType("bigint")
                        .HasColumnName("ap");

                    b.Property<decimal>("BaseExp")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("base_exp");

                    b.Property<int>("BaseLevel")
                        .HasColumnType("int")
                        .HasColumnName("base_level");

                    b.Property<int>("Body")
                        .HasColumnType("int")
                        .HasColumnName("body");

                    b.Property<byte>("BodyDirection")
                        .HasColumnType("tinyint")
                        .HasColumnName("body_direction");

                    b.Property<byte>("CharNum")
                        .HasColumnType("tinyint")
                        .HasColumnName("char_num");

                    b.Property<long>("Child")
                        .HasColumnType("bigint")
                        .HasColumnName("child");

                    b.Property<long>("ClanId")
                        .HasColumnType("bigint")
                        .HasColumnName("clan_id");

                    b.Property<int>("Class")
                        .HasColumnType("int")
                        .HasColumnName("class");

                    b.Property<int>("ClothesColor")
                        .HasColumnType("int")
                        .HasColumnName("clothes_color");

                    b.Property<int>("Con")
                        .HasColumnType("int")
                        .HasColumnName("con");

                    b.Property<int>("Crt")
                        .HasColumnType("int")
                        .HasColumnName("crt");

                    b.Property<long>("DeleteDate")
                        .HasColumnType("bigint")
                        .HasColumnName("delete_date");

                    b.Property<int>("Dex")
                        .HasColumnType("int")
                        .HasColumnName("dex");

                    b.Property<int>("DisableCall")
                        .HasColumnType("int")
                        .HasColumnName("disable_call");

                    b.Property<byte>("DisablePartyInvite")
                        .HasColumnType("tinyint")
                        .HasColumnName("disable_partyinvite");

                    b.Property<byte>("DisableShowCostumes")
                        .HasColumnType("tinyint")
                        .HasColumnName("disable_showcostumes");

                    b.Property<long>("ElementalId")
                        .HasColumnType("bigint")
                        .HasColumnName("elemental_id");

                    b.Property<long>("Fame")
                        .HasColumnType("bigint")
                        .HasColumnName("fame");

                    b.Property<long>("Father")
                        .HasColumnType("bigint")
                        .HasColumnName("father");

                    b.Property<byte>("Font")
                        .HasColumnType("tinyint")
                        .HasColumnName("font");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<byte>("Hair")
                        .HasColumnType("tinyint")
                        .HasColumnName("hair");

                    b.Property<int>("HairColor")
                        .HasColumnType("int")
                        .HasColumnName("hair_color");

                    b.Property<int>("HeadBottom")
                        .HasColumnType("int")
                        .HasColumnName("head_bottom");

                    b.Property<int>("HeadMid")
                        .HasColumnType("int")
                        .HasColumnName("head_mid");

                    b.Property<int>("HeadTop")
                        .HasColumnType("int")
                        .HasColumnName("head_top");

                    b.Property<long>("HomunId")
                        .HasColumnType("bigint")
                        .HasColumnName("homun_id");

                    b.Property<byte>("HotkeyRowShift")
                        .HasColumnType("tinyint")
                        .HasColumnName("hotkey_rowshift");

                    b.Property<byte>("HotkeyRowShift2")
                        .HasColumnType("tinyint")
                        .HasColumnName("hotkey_rowshift2");

                    b.Property<long>("Hp")
                        .HasColumnType("bigint")
                        .HasColumnName("hp");

                    b.Property<int>("Int")
                        .HasColumnType("int")
                        .HasColumnName("int");

                    b.Property<short>("InventorySlots")
                        .HasColumnType("smallint")
                        .HasColumnName("inventory_slots");

                    b.Property<decimal>("JobExp")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("job_exp");

                    b.Property<int>("JobLevel")
                        .HasColumnType("int")
                        .HasColumnName("job_level");

                    b.Property<byte>("Karma")
                        .HasColumnType("tinyint")
                        .HasColumnName("karma");

                    b.Property<long>("LastInstanceId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_instanceid");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login");

                    b.Property<string>("LastMap")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("last_map");

                    b.Property<int>("LastX")
                        .HasColumnType("int")
                        .HasColumnName("last_x");

                    b.Property<int>("LastY")
                        .HasColumnType("int")
                        .HasColumnName("last_y");

                    b.Property<int>("Luk")
                        .HasColumnType("int")
                        .HasColumnName("luk");

                    b.Property<short>("Manner")
                        .HasColumnType("smallint")
                        .HasColumnName("manner");

                    b.Property<long>("MaxAp")
                        .HasColumnType("bigint")
                        .HasColumnName("max_ap");

                    b.Property<long>("MaxHp")
                        .HasColumnType("bigint")
                        .HasColumnName("max_hp");

                    b.Property<long>("MaxSp")
                        .HasColumnType("bigint")
                        .HasColumnName("max_sp");

                    b.Property<long>("Mother")
                        .HasColumnType("bigint")
                        .HasColumnName("mother");

                    b.Property<long>("Moves")
                        .HasColumnType("bigint")
                        .HasColumnName("moves");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("name");

                    b.Property<byte>("Online")
                        .HasColumnType("tinyint")
                        .HasColumnName("online");

                    b.Property<long>("Option")
                        .HasColumnType("bigint")
                        .HasColumnName("option");

                    b.Property<long>("PartnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("partner_id");

                    b.Property<long>("PartyId")
                        .HasColumnType("bigint")
                        .HasColumnName("party_id");

                    b.Property<long>("PetId")
                        .HasColumnType("bigint")
                        .HasColumnName("pet_id");

                    b.Property<int>("Pow")
                        .HasColumnType("int")
                        .HasColumnName("pow");

                    b.Property<int>("Rename")
                        .HasColumnType("int")
                        .HasColumnName("rename");

                    b.Property<int>("Robe")
                        .HasColumnType("int")
                        .HasColumnName("robe");

                    b.Property<string>("SaveMap")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("save_map");

                    b.Property<int>("SaveX")
                        .HasColumnType("int")
                        .HasColumnName("save_x");

                    b.Property<int>("SaveY")
                        .HasColumnType("int")
                        .HasColumnName("save_y");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("sex");

                    b.Property<int>("Shield")
                        .HasColumnType("int")
                        .HasColumnName("shield");

                    b.Property<int>("ShowEquip")
                        .HasColumnType("int")
                        .HasColumnName("show_equip");

                    b.Property<long>("SkillPoint")
                        .HasColumnType("bigint")
                        .HasColumnName("skill_point");

                    b.Property<long>("Sp")
                        .HasColumnType("bigint")
                        .HasColumnName("sp");

                    b.Property<int>("Spl")
                        .HasColumnType("int")
                        .HasColumnName("spl");

                    b.Property<int>("Sta")
                        .HasColumnType("int")
                        .HasColumnName("sta");

                    b.Property<long>("StatusPoint")
                        .HasColumnType("bigint")
                        .HasColumnName("status_point");

                    b.Property<int>("Str")
                        .HasColumnType("int")
                        .HasColumnName("str");

                    b.Property<long>("TitleId")
                        .HasColumnType("bigint")
                        .HasColumnName("title_id");

                    b.Property<long>("TraitPoint")
                        .HasColumnType("bigint")
                        .HasColumnName("trait_point");

                    b.Property<long>("UnbanTime")
                        .HasColumnType("bigint")
                        .HasColumnName("unban_time");

                    b.Property<long>("UniqueItemCounter")
                        .HasColumnType("bigint")
                        .HasColumnName("uniqueitem_counter");

                    b.Property<int>("Vit")
                        .HasColumnType("int")
                        .HasColumnName("vit");

                    b.Property<int>("Weapon")
                        .HasColumnType("int")
                        .HasColumnName("weapon");

                    b.Property<int>("Wis")
                        .HasColumnType("int")
                        .HasColumnName("wis");

                    b.Property<long>("Zeny")
                        .HasColumnType("bigint")
                        .HasColumnName("zeny");

                    b.HasKey("CharId");

                    b.HasIndex("AccountId");

                    b.HasIndex("GuildId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Online");

                    b.HasIndex("PartyId");

                    b.ToTable("char", (string)null);
                });

            modelBuilder.Entity("Athena.Net.CharServer.Db.Entities.CharHotkey", b =>
                {
                    b.Property<long>("CharId")
                        .HasColumnType("bigint")
                        .HasColumnName("char_id");

                    b.Property<byte>("Hotkey")
                        .HasColumnType("tinyint")
                        .HasColumnName("hotkey");

                    b.Property<long>("ItemSkillId")
                        .HasColumnType("bigint")
                        .HasColumnName("itemskill_id");

                    b.Property<byte>("SkillLevel")
                        .HasColumnType("tinyint")
                        .HasColumnName("skill_lvl");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint")
                        .HasColumnName("type");

                    b.HasKey("CharId", "Hotkey");

                    b.HasIndex("CharId");

                    b.ToTable("hotkey", (string)null);
                });

            modelBuilder.Entity("Athena.Net.CharServer.Db.Entities.CharInventory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<byte>("Attribute")
                        .HasColumnType("tinyint")
                        .HasColumnName("attribute");

                    b.Property<byte>("Bound")
                        .HasColumnType("tinyint")
                        .HasColumnName("bound");

                    b.Property<long>("Card0")
                        .HasColumnType("bigint")
                        .HasColumnName("card0");

                    b.Property<long>("Card1")
                        .HasColumnType("bigint")
                        .HasColumnName("card1");

                    b.Property<long>("Card2")
                        .HasColumnType("bigint")
                        .HasColumnName("card2");

                    b.Property<long>("Card3")
                        .HasColumnType("bigint")
                        .HasColumnName("card3");

                    b.Property<long>("CharId")
                        .HasColumnType("bigint")
                        .HasColumnName("char_id");

                    b.Property<byte>("EnchantGrade")
                        .HasColumnType("tinyint")
                        .HasColumnName("enchantgrade");

                    b.Property<long>("Equip")
                        .HasColumnType("bigint")
                        .HasColumnName("equip");

                    b.Property<long>("EquipSwitch")
                        .HasColumnType("bigint")
                        .HasColumnName("equip_switch");

                    b.Property<long>("ExpireTime")
                        .HasColumnType("bigint")
                        .HasColumnName("expire_time");

                    b.Property<byte>("Favorite")
                        .HasColumnType("tinyint")
                        .HasColumnName("favorite");

                    b.Property<short>("Identify")
                        .HasColumnType("smallint")
                        .HasColumnName("identify");

                    b.Property<long>("NameId")
                        .HasColumnType("bigint")
                        .HasColumnName("nameid");

                    b.Property<short>("OptionId0")
                        .HasColumnType("smallint")
                        .HasColumnName("option_id0");

                    b.Property<short>("OptionId1")
                        .HasColumnType("smallint")
                        .HasColumnName("option_id1");

                    b.Property<short>("OptionId2")
                        .HasColumnType("smallint")
                        .HasColumnName("option_id2");

                    b.Property<short>("OptionId3")
                        .HasColumnType("smallint")
                        .HasColumnName("option_id3");

                    b.Property<short>("OptionId4")
                        .HasColumnType("smallint")
                        .HasColumnName("option_id4");

                    b.Property<byte>("OptionParm0")
                        .HasColumnType("tinyint")
                        .HasColumnName("option_parm0");

                    b.Property<byte>("OptionParm1")
                        .HasColumnType("tinyint")
                        .HasColumnName("option_parm1");

                    b.Property<byte>("OptionParm2")
                        .HasColumnType("tinyint")
                        .HasColumnName("option_parm2");

                    b.Property<byte>("OptionParm3")
                        .HasColumnType("tinyint")
                        .HasColumnName("option_parm3");

                    b.Property<byte>("OptionParm4")
                        .HasColumnType("tinyint")
                        .HasColumnName("option_parm4");

                    b.Property<short>("OptionVal0")
                        .HasColumnType("smallint")
                        .HasColumnName("option_val0");

                    b.Property<short>("OptionVal1")
                        .HasColumnType("smallint")
                        .HasColumnName("option_val1");

                    b.Property<short>("OptionVal2")
                        .HasColumnType("smallint")
                        .HasColumnName("option_val2");

                    b.Property<short>("OptionVal3")
                        .HasColumnType("smallint")
                        .HasColumnName("option_val3");

                    b.Property<short>("OptionVal4")
                        .HasColumnType("smallint")
                        .HasColumnName("option_val4");

                    b.Property<byte>("Refine")
                        .HasColumnType("tinyint")
                        .HasColumnName("refine");

                    b.Property<decimal>("UniqueId")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("unique_id");

                    b.HasKey("Id");

                    b.HasIndex("CharId");

                    b.ToTable("inventory", (string)null);
                });

            modelBuilder.Entity("Athena.Net.CharServer.Db.Entities.CharQuest", b =>
                {
                    b.Property<long>("CharId")
                        .HasColumnType("bigint")
                        .HasColumnName("char_id");

                    b.Property<long>("QuestId")
                        .HasColumnType("bigint")
                        .HasColumnName("quest_id");

                    b.Property<long>("Count1")
                        .HasColumnType("bigint")
                        .HasColumnName("count1");

                    b.Property<long>("Count2")
                        .HasColumnType("bigint")
                        .HasColumnName("count2");

                    b.Property<long>("Count3")
                        .HasColumnType("bigint")
                        .HasColumnName("count3");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("state");

                    b.Property<long>("Time")
                        .HasColumnType("bigint")
                        .HasColumnName("time");

                    b.HasKey("CharId", "QuestId");

                    b.ToTable("quest", (string)null);
                });

            modelBuilder.Entity("Athena.Net.CharServer.Db.Entities.CharSkill", b =>
                {
                    b.Property<long>("CharId")
                        .HasColumnType("bigint")
                        .HasColumnName("char_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<byte>("Flag")
                        .HasColumnType("tinyint")
                        .HasColumnName("flag");

                    b.Property<byte>("SkillLevel")
                        .HasColumnType("tinyint")
                        .HasColumnName("lv");

                    b.HasKey("CharId", "SkillId");

                    b.HasIndex("CharId");

                    b.ToTable("skill", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
